"""add_saved_lessons_table

Revision ID: d21b448e5538
Revises: 33e45132d6eb
Create Date: 2025-12-24 16:49:56.949548+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd21b448e5538'
down_revision = '33e45132d6eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('difficulty_level', sa.String(), nullable=True),
    sa.Column('lesson_data', sa.JSON(), nullable=False),
    sa.Column('youtube_video_id', sa.String(), nullable=True),
    sa.Column('youtube_video_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_lessons_id'), 'saved_lessons', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_lessons_id'), table_name='saved_lessons')
    op.drop_table('saved_lessons')
    # ### end Alembic commands ###


