"""Initial database setup

Revision ID: eb801a821e28
Revises: add_lesson_chat
Create Date: 2026-01-14 10:46:06.697603+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb801a821e28'
down_revision = 'add_lesson_chat'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


