"""add_past_questions_table

Revision ID: add_past_questions
Revises: eb801a821e28
Create Date: 2026-01-15 12:00:00.000000+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'add_past_questions'
down_revision = 'eb801a821e28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('past_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_answer', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('source_pdf', sa.String(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_past_questions_id'), 'past_questions', ['id'], unique=False)
    op.create_index('idx_exam_subject_year', 'past_questions', ['exam_type', 'subject', 'year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_exam_subject_year', table_name='past_questions')
    op.drop_index(op.f('ix_past_questions_id'), table_name='past_questions')
    op.drop_table('past_questions')
    # ### end Alembic commands ###
